### PR TITLE
notifiers: add mailgun and pushover

### PR DESCRIPTION
**Pull request by mattberther**

### CODE REVIEW

**Comment by titpetric** [comment]
Hi. Due to recent changes, this PR has been outdated. Could you rebase/re-implement the checkers against the structure in the master branch? I'd like to have this in, if you're willing to update this.

**Comment by mattberther** [comment]
@titpetric Rebase complete. Please review and let me know if you have any changes.

**Comment by titpetric** [comment]
LGTM: update appreciated!

@beyang PTAL, let me know if you need a CLA for this. Not sure how strict you need to be with it.

**Comment by beyang** [comment]
Seeing if we can streamline this a bit: https://github.com/sourcegraph/checkup/pull/129

**Comment by beyang** [comment]
@mattberther can you post a message acknowledging the DCO applies to this PR (as the DCO file did not exist at the time you opened the PR)? That way, we can merge this without asking to sign the CLA.

**Comment by mattberther** [comment]
@beyang the DCO applies to this PR

**Comment by titpetric** [comment]
Thank you for your contribution!

**Comment by titpetric** [comment]
Key @mattberther - just a heads up, I'll be updating the definition for `to` to take an array of recipients. It will land shortly, just letting you know to avoid possible breaks on your side.

**Pull request merged**
