### PR TITLE
Document StorageReader interface

### PR DESCRIPTION
**Pull request by McKael**
Document StorageReader interface as suggested by @shurcooL in https://github.com/sourcegraph/checkup/pull/58

### CODE REVIEW

**Comment by mholt** [comment]
Woah, epic segfault in the test! That is not your fault - that is due to a change in the google/go-github package. The tests passed for me locally, then when I ran `go get -u` on that package the tests failed, so it must be a new breakage upstream.

**Comment by mholt** [comment]
@McKael If you merge in the latest change, the tests will pass and I won't feel dirty about merging this. :wink:

**Comment by mholt** [comment]
Nevermind! Re-running the tests makes it work. We're all good here. Thanks!

**Comment by McKael** [comment]
Thanks!

**Pull request merged**
