### PR TITLE
Support for exporters

### PR DESCRIPTION
**Pull request by mcdafydd**
Adds support for exporting test result data to external services.  Allows external services to perform additional decision making or correlate with other data sources.  Initial PR integrates with Azure Application Insights.

### CODE REVIEW

**Comment by titpetric** [comment]
Let’s start with the obvious question: why not just write a storage plugin for azure app insights?

**Comment by mcdafydd** [comment]
Now that I'm writing about it, that would be fine.  I initially landed here because:

1. I'm working on an azure blob storage plugin, which would be very similar to s3, and Application Insights feels like a fundamentally different use case than just storage
2. I wanted this to run with or without the `--store` flag so I could choose to capture the stdout results as well.  But, I suppose a serialized stdout storage plugin would be more useful in that regard than human-readable output,

If you're willing to consider merging, I'll rewrite this as a storage plugin.

Thanks!

**Comment by titpetric** [comment]
If you’re willing, both the azure app insights and the stdout plugins seem
very cool additions! I’m pretty sure I need to clean up the rest of checkup
in regards to logging, so it doesn’t interfere with the stdout store.

Please be sure to rebase, and give a little footnote for changes outside of
the storage plugins in the comments. I’ve seen a few line change regarding
certstores in tcp/tls but haven’t tracked the godoc to verify if they make
sense in that context. A tweet sized explanation why it’s needed and if it
closes any issues is appreciated.

Thank you :)

**Comment by mcdafydd** [comment]
Replacing with #132

**Pull request closed without merging**
